# Generated by Django 3.1.12 on 2025-11-21 02:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20251121_0806'),
        ('accounts', '0002_auto_20251121_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_marks', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('ai_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('faculty_marks', models.FloatField(blank=True, null=True)),
                ('faculty_feedback', models.TextField(blank=True, null=True)),
                ('faculty_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation_criteria', models.TextField(help_text='JSON string of criteria used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria_name', models.CharField(max_length=200)),
                ('criteria_description', models.TextField()),
                ('max_marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='accounts.faculty')),
            ],
            options={
                'verbose_name_plural': 'Evaluation Criteria',
            },
        ),
    ]
